### ISSUE TITLE
Another implemention and new model support

### ISSUE THREAD

**Issue by miemiekurisu** [fijam/gmdrec#30]
Hi @fijam ~
Firstly, thank you very much for this project, I've learned a lot from it.

And I've tried to rebuilt another version, for learn and fun :) (and some other reasons, such like it's very hard to get the MCP2221AxSL here as well as my N910's NET port is broken - strange, but I don't know why, LOL)

I tried the key set and controlls N710/NF810, it works well.

But I've found the button operation is very different in some model, such like my broken N910.
The play key can't  be used to confirm the letter and move to the next, but luckly I found another way to input. The GROUP_PLUS key can move current input to next and insert a blank, and have to start from the head of alphabet.

So I reverse the name and input from the last charecter, it works well then.

BTW, I'm not sure why my R55 didn't work, it seems not to accept any key input, 
but the official EL33 works (just key, display doesn't show properly, of course), 
maybe that I change it to li-ion battery to avoid the famous "low battery issue" cause this  problem.

I think you may need these infomation when you enhance this project.

**Comment by fijam** [comment]
Hi,

Thanks for reaching out. Officially, the earliest supported model is R37. The user manual for R55 does not talk about editing titles from the remote so I don't know how what buttons need to be pressed or if it's possible at all.

Personally, I am not interested in supporting later NetMD models but if you can come up with a pull request (and it doesn't introduce too much complexity) I will look into adding it. Feel free to look into https://github.com/fijam/gmdrec/tree/main/definitions to see how different models are defined.
