### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by spbkaizo** [fijam/gmdrec#33]
I suspect I'm doing something dim here, but I'm struggling to get the command line arguments correct.  For example, I though this was the correct way to call it, but the playlist just returns the string I put there:

```
<simonb@odin:~/src/gmdrec>
zsh 727 [2]  (git)-[main]-% python mdrec.py recorder R909/R910/N1
Total playlist duration: 0:41:41
The playlist contains the following tracks:
['recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder',
 'recorder']
Wait for REC Standby...
Cleaning up.
Bye!

```

Calling it like this causes something else odd:

```
zsh 724 [2]  (git)-[main]-% python mdrec.py label  "R70 through N707" 
Total playlist duration: 0:41:41
The playlist contains the following tracks:
['label',
 'label',
 'label',
 'label',
 'label',
 'label',
 'label',
 'label',
 'label',
 'label',
 'label']
Wait for REC Standby...
Cleaning up.
Bye!
```

Here's one which errors, showing me the correct usage, but I don't see it explicitly having a recorder option?

```
zsh 728  (git)-[main]-% python mdrec.py label foo recorder R909/R910/N1
usage: mdrec.py [-h] [--disc-title DISC_TITLE] [--language-hint LANGUAGE_CODE] [--only_label {OFF,ON,ERASE}] [--no-tmarks] label {R55/R37,R55/R37 JPN,R70 through N707,R70 through N707 JPN,R909/R910/N1,R909/R910/N1 JPN}
mdrec.py: error: argument recorder: invalid choice: 'foo' (choose from 'R55/R37', 'R55/R37 JPN', 'R70 through N707', 'R70 through N707 JPN', 'R909/R910/N1', 'R909/R910/N1 JPN')
```

What's the correct way to run this utility please ?

**Comment by fijam** [comment]
Oh I suppose the command line parameters are not obvious at all... I guess I will need to add some examples.

For now try something like `python mdrec.py "%artist% - %title%" "R70 through N707"`

**Comment by fijam** [comment]
Did you succeed? It seems like you managed to get everything else working correctly.

**Comment by spbkaizo** [comment]
I've not had a chance to test this yet sorry.

Happy for you to close this issue though, and I'll report back in the other one.
